[2024-07-08T00:48:14.915-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T00:48:14.938-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 manual__2024-07-08T03:43:01.869522+00:00 [queued]>
[2024-07-08T00:48:14.958-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 manual__2024-07-08T03:43:01.869522+00:00 [queued]>
[2024-07-08T00:48:14.960-0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T00:48:15.002-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_csv_to_s3> on 2024-07-08 03:43:01.869522+00:00
[2024-07-08T00:48:15.039-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'upload_multiple_csvs_to_s3_dag', 'upload_csv_to_s3', 'manual__2024-07-08T03:43:01.869522+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_s3.py', '--cfg-path', '/tmp/tmpxzfx177i']
[2024-07-08T00:48:15.044-0300] {standard_task_runner.py:91} INFO - Job 22: Subtask upload_csv_to_s3
[2024-07-08T00:48:15.051-0300] {logging_mixin.py:188} WARNING - /home/johnny/airflow/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=66060) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T00:48:15.052-0300] {standard_task_runner.py:63} INFO - Started process 66073 to run task
[2024-07-08T00:48:15.162-0300] {task_command.py:426} INFO - Running <TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 manual__2024-07-08T03:43:01.869522+00:00 [running]> on host LAPTOP-V3FS4O6J.
[2024-07-08T00:48:15.307-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='upload_multiple_csvs_to_s3_dag' AIRFLOW_CTX_TASK_ID='upload_csv_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-08T03:43:01.869522+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-08T03:43:01.869522+00:00'
[2024-07-08T00:48:15.311-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T00:48:15.329-0300] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-07-08T00:48:15.330-0300] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-08T00:48:16.133-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T00:48:16.134-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/dags/upload_to_s3.py", line 22, in upload_csv_to_s3
    s3_hook.load_file(
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1098, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/johnny/airflow/lib/python3.12/site-packages/boto3/s3/inject.py", line 145, in upload_file
    return transfer.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/boto3/s3/transfer.py", line 372, in upload_file
    future.result()
  File "/home/johnny/airflow/lib/python3.12/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/johnny/airflow/lib/python3.12/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/s3transfer/upload.py", line 764, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/client.py", line 958, in _make_api_call
    api_params = self._emit_api_params(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/client.py", line 1084, in _emit_api_params
    self.meta.events.emit(
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/botocore/handlers.py", line 288, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "arn:aws:s3:::curso-eng-vendas1234/teste-esfera/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2024-07-08T00:48:16.144-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=upload_multiple_csvs_to_s3_dag, task_id=upload_csv_to_s3, run_id=manual__2024-07-08T03:43:01.869522+00:00, execution_date=20240708T034301, start_date=20240708T034814, end_date=20240708T034816
[2024-07-08T00:48:16.176-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task upload_csv_to_s3 (Parameter validation failed:
Invalid bucket name "arn:aws:s3:::curso-eng-vendas1234/teste-esfera/": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"; 66073)
[2024-07-08T00:48:16.217-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T00:48:16.249-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T00:48:16.251-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
