[2024-07-08T00:11:24.172-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T00:11:24.195-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T00:11:24.209-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T00:11:24.210-0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-08T00:11:24.242-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_csv_to_s3> on 2024-07-07 00:00:00+00:00
[2024-07-08T00:11:24.257-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'upload_multiple_csvs_to_s3_dag', 'upload_csv_to_s3', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_s3.py', '--cfg-path', '/tmp/tmpawyyguwf']
[2024-07-08T00:11:24.261-0300] {standard_task_runner.py:91} INFO - Job 14: Subtask upload_csv_to_s3
[2024-07-08T00:11:24.268-0300] {logging_mixin.py:188} WARNING - /home/johnny/airflow/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=62263) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T00:11:24.269-0300] {standard_task_runner.py:63} INFO - Started process 62275 to run task
[2024-07-08T00:11:24.339-0300] {task_command.py:426} INFO - Running <TaskInstance: upload_multiple_csvs_to_s3_dag.upload_csv_to_s3 scheduled__2024-07-07T00:00:00+00:00 [running]> on host LAPTOP-V3FS4O6J.
[2024-07-08T00:11:24.480-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='upload_multiple_csvs_to_s3_dag' AIRFLOW_CTX_TASK_ID='upload_csv_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-08T00:11:24.483-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T00:11:24.485-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T00:11:24.486-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnny/airflow/dags/upload_to_s3.py", line 13, in upload_csv_to_s3
    for filename in os.listdir(local_folder_path):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/airflow/data'
[2024-07-08T00:11:24.494-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=upload_multiple_csvs_to_s3_dag, task_id=upload_csv_to_s3, run_id=scheduled__2024-07-07T00:00:00+00:00, execution_date=20240707T000000, start_date=20240708T031124, end_date=20240708T031124
[2024-07-08T00:11:24.513-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task upload_csv_to_s3 ([Errno 2] No such file or directory: '~/airflow/data'; 62275)
[2024-07-08T00:11:24.568-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T00:11:24.593-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-08T00:11:24.594-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
